### ISSUE TITLE
Dropdown not getting triggered in list-candidates

### ISSUE THREAD

**Issue by vrajroham** [madhura29/myvizo#3]
Dropdown is not shown in candidate list view.
[These lines are causing the issue](https://github.com/madhura29/myvizo/blob/dev/resources/views/all-user.blade.php#L4-L6)

### Description 
You are adding this files multiple times and the location of files is invalid. Always CSS files should be on `<head>` and JS files should be always at the last of page. 

TO overcome this issue you can take help of `sections` in blade templating engine.

**Comment by rahulrahane1995** [comment]
solved this issue by putting a .css and js in proper location.
